version: '3.8'

services:
  data-base:
    image: mysql:8.0.36-bookworm
    command: --innodb_force_recovery=0
    container_name: database
    restart: always
    expose:
      - 3307
      - 33060
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - crudg-data:/var/lib/mysql
  
  crud-generator:
    container_name: crud-generator
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:$APP_PORT
    depends_on:
      data-base:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - APP_PORT=$APP_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
    stdin_open: true
    tty: true

volumes:
  crudg-data: